site_name: mittens
site_description: 'Mittens - kubectl plugin to interactively proxy Kubernetes Services with mitmproxy'
repo_name: 'Lappihuan/mittens'
repo_url: https://github.com/Lappihuan/mittens
copyright: 'Copyright &copy; 2020 Soluble - Apache License 2.0'
docs_dir: docs
edit_uri: ""
theme:
  name: material
  palette:
    primary: blue
    accent: orange
extra_css:
  - styles/website.css
nav:
  - Introduction: README.md
  - 'Getting Started':
    - Installation: getting_started/installation.md
    - 'Quick Start': getting_started/quick-start.md
    - Usage: getting_started/usage.md
    - K9s Integration: getting_started/k9s-integration.md
  - FAQ: FAQ.md
  - Development:
    - Overview: mittens_development/README.md
    - Contributing: mittens_development/contributing.md
    - TODOs: mittens_development/TODOs.md
    - Caveats: mittens_development/caveats.md
    - Scripts: mittens_development/scripts.md
  - About: about.md
  - Acknowledgements: acknowledgements.md
markdown_extensions:
  - toc:
      permalink: []
  - admonition
  - codehilite:
      guess_lang: false
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/Lappihuan
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/solubleai
