name: Push ghcr.io mitmproxy image
on:
  # rebuild and push the container, updating dependencies, every 6 hours
  schedule:
    - cron: '0 */6 * * *'
  push:
    branches: [master]
    paths:
    - 'proxies/mitmproxy'

permissions:
  packages: write

jobs:
  mitmproxy-image:
    timeout-minutes: 10
    name: Build and push mitmproxy to GHCR
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Build and push to GHCR
      uses: docker/build-push-action@v6
      with:
        context: ./proxies/mitmproxy
        push: true
        registry: ghcr.io
        tags: |
          ghcr.io/${{ github.repository_owner }}/kubetap-mitmproxy:latest
          ghcr.io/${{ github.repository_owner }}/kubetap-mitmproxy:${{ github.sha }}
